# Source files
SRC = logical_in.cpp
SRC += debounce.cpp
TEST_SRC = logical_in_test.cpp
LIB := lib_logical_in.a
TEST_EXEC := logical_in_test
INCLUDE_PATH := ../debounce

# call include file
include ../makefile_include
